### ISSUE TITLE
feat: Post CRUD 작업 및 테스트 코드 작성

### ISSUE THREAD

**Issue by jongwanra** [f-lab-edu/outfit-of-the-day#16]
## ✅ *Todo*
- [x]  post 추가
- [x]  post 수정
- [x]  post 삭제
- [x]  post 조회
- [x]  post 추가 테스트 코드
- [x]  post 수정 테스트 코드
- [x]  post 삭제 테스트 코드
- [x]  post 조회 테스트 코드
